/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package math;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import joinery.*;

import math.App;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.ZonedDateTime;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import static math.App.buildTableModel;

/**
 *
 * @author japar
 */
public class fact extends javax.swing.JFrame {

 private final String url = "jdbc:postgresql://localhost/postgres";
    private final String user = "postgres";
    private final String password = "postgres";
     public Connection connect() {
        Connection conn = null;
        try {
            conn = DriverManager.getConnection(url, user, password);
            Statement stmt = conn.createStatement();
            ResultSet rs;
            rs = stmt.executeQuery("SELECT * FROM inventario");
            while ( rs.next() ) {
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
 
        return conn;

    }
    public fact() {
        initComponents();
    }
//    public Dataframe s(){}
        
public Statement getdatacombobox()
        
{
     Statement combop=null ;
        try {
            Connection conn = connect();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("select distinct(tipo) as tipo from public.inventario");
            while(rs.next()){App ab= new App();
            comboproducto.addItem(rs.getString("tipo"));
            if(((DefaultComboBoxModel)comboproducto.getModel()).getIndexOf(rs.getString("tipo")) < 0) {
                comboproducto.addItem(rs.getString("tipo" ));
}
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(null, e);
    }
 
        return combop;
}     
public Statement consec()
        
{
     Statement tivo=null ;
        try {
            Connection conn = connect();
            Statement stmt = conn.createStatement();
            String query ="select max(fact_id::int)+1 as id  from public.fact1";
            ResultSet rs = stmt.executeQuery(query);
            while(rs.next()){App ab= new App();
            consecutivofact.setText(rs.getString("id"));
        
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(null, e);
    }
 
        return tivo;
}


public Statement fact()
        
{
            String conse=consecutivofact.getText();

    Statement finali=null ;
        try {
            Connection conn = connect();
            Statement stmt = conn.createStatement();
            String query ="select sum(calctotaliva::int) as total from public.facturatotal where fact_id='"+conse+"';";
            ResultSet rs = stmt.executeQuery(query);
                       
           
               JTable table = new JTable(buildTableModel(rs));
               JFrame frame = new JFrame("Debe cobrar");
               
               JOptionPane.showMessageDialog(frame, new JScrollPane(table));
  
  
        
        

    } catch (Exception e) {

        JOptionPane.showMessageDialog(null, e);
    }
 
        return finali;
}


    public void leerTabla(){

    try{
 Connection conn = connect();
  String queryco =  "INSERT INTO fact1 (fact_id,product_name,cantidad, preciouni, iva, created_on, product_id) values(?,?,?,?,?,?,?)";
  ZonedDateTime zdt = ZonedDateTime.now();
  
  PreparedStatement pst = conn.prepareStatement(queryco);
   pst.setString(1,consecutivofact.getText() );
   pst.setString(2,comboproducto.getSelectedItem().toString());
   pst.setString(3,cantidad.getText() );
   pst.setString(4,precio.getText() );
   pst.setString(5,iva.getText() );
   pst.setString(6,zdt.toString() );
   pst.setString(7,idproduct.getText());
    pst.execute();
  JOptionPane.showMessageDialog(null, "Successfully Save");
}
catch(Exception e){
  JOptionPane.showMessageDialog(this,e.getMessage());
}
 

}
//end of happi
//end of happi
//end of happi

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        boton = new javax.swing.JButton();
        comboproducto = new javax.swing.JComboBox<>();
        precio = new javax.swing.JTextField();
        consecutivofact = new javax.swing.JTextField();
        iva = new javax.swing.JTextField();
        idproduct = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        cantidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cargar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Consecutivo");

        jLabel2.setText("Id producto");

        jLabel3.setText("Seleccione un producto");

        jLabel4.setText("Precio unitario");

        jLabel5.setText("IVA");

        boton.setText("Agregar");
        boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMouseClicked(evt);
            }
        });
        boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActionPerformed(evt);
            }
        });

        comboproducto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboproductoItemStateChanged(evt);
            }
        });
        comboproducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboproductoMouseClicked(evt);
            }
        });

        precio.setEditable(false);

        consecutivofact.setEditable(false);
        consecutivofact.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                consecutivofactMouseMoved(evt);
            }
        });

        iva.setEditable(false);

        idproduct.setEditable(false);

        tabla.setAutoCreateRowSorter(true);
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "consecutivo", "nombre producto", "cantidad", "precio", "iva", "create on", "codigo de producto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setToolTipText("");
        tabla.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tabla);
        tabla.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        cantidad.setText(" ");

        jLabel6.setText("Cantidad");

        cargar.setText("Finalizar Transaccion");
        cargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cargarMouseClicked(evt);
            }
        });
        cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(idproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(consecutivofact, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(comboproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(boton)
                        .addGap(46, 46, 46)
                        .addComponent(cargar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(iva, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(comboproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consecutivofact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idproduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(iva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton)
                    .addComponent(cargar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//        private void comboproductoMouseClicked(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:

  //      }
    private void botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActionPerformed
        // TODO add your handling code here:
         String conse= consecutivofact.getText();
        String pname= (String) comboproducto.getSelectedItem();
        String cantt= cantidad.getText();
        String preciot= precio.getText();
        String ivat= iva.getText();
        ZonedDateTime zdt = ZonedDateTime.now();
        String ipt= idproduct.getText();
        

            Object[] row = { conse, pname, cantt, preciot,ivat,zdt,ipt };

    DefaultTableModel model = (DefaultTableModel) tabla.getModel();

    model.addRow(row);
    leerTabla();

    }//GEN-LAST:event_botonActionPerformed

    private void comboproductoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboproductoItemStateChanged
        // TODO add your handling code here:
        try{
        Connection conn = connect();
        Statement stmt = conn.createStatement();   
    String value = comboproducto.getSelectedItem().toString();
    String query = "Select * from inventario where tipo= \'"+value+"\';";
    ResultSet rs = stmt.executeQuery(query);    
    rs.next();
    idproduct.setText(rs.getString("inv_id"));
    iva.setText(rs.getString("iva"));
    precio.setText(rs.getString("precio"));
    
    }
        
catch (Exception e) {

        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_comboproductoItemStateChanged

    
    private void comboproductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboproductoMouseClicked
        // TODO add your handling code here:
                getdatacombobox();
    }//GEN-LAST:event_comboproductoMouseClicked

    private void consecutivofactMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consecutivofactMouseMoved
        // TODO add your handling code here:
        consec();
    }//GEN-LAST:event_consecutivofactMouseMoved

    private void botonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMouseClicked
        // TODO add your handling code here:
                // TODO add your handling code here:
                
       
        
        


      
    }//GEN-LAST:event_botonMouseClicked

    private void cargarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargarMouseClicked
       
        
    }//GEN-LAST:event_cargarMouseClicked

    private void cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarActionPerformed
        // TODO add your handling code here:
fact();

    }//GEN-LAST:event_cargarActionPerformed




   // private void comboproductoItemStateChanged(java.awt.event.ItemEvent evt) {                                               
        // TODO add your handling code here:
          
    //()}
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

//        /* Create and display the form */

         fact fact1 = new fact();
       fact1.getdatacombobox();
        //fact1.consec();
        //fact1.leerTabla();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fact().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton;
    private javax.swing.JTextField cantidad;
    private javax.swing.JButton cargar;
    private javax.swing.JComboBox<String> comboproducto;
    private javax.swing.JTextField consecutivofact;
    private javax.swing.JTextField idproduct;
    private javax.swing.JTextField iva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField precio;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables

    private int convertRowIndexToModel(int row) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}